__author__ = 'gmgilmore'

{'stream_delay_s': 120, 'spectators': 167, 'league_id': 2090, 'lobby_id': 23975536729840103,
 'series_type': 0,
 'scoreboard': {'duration': 2087.677734375, 'radiant': {'abilities': [{'ability_id': 5154, 'ability_level': 4},
                                                                      {'ability_id': 5155, 'ability_level': 4},
                                                                      {'ability_id': 5156, 'ability_level': 4},
                                                                      {'ability_id': 5157, 'ability_level': 3},
                                                                      {'ability_id': 5002, 'ability_level': 2}],
                                                        'bans': [{'hero_id': 29}, {'hero_id': 2}, {'hero_id': 12},
                                                                 {'hero_id': 96},
                                                                 {'hero_id': 8}], 'barracks_state': 60,
                                                        'picks': [{'hero_id': 99}, {'hero_id': 15}, {'hero_id': 35},
                                                                  {'hero_id': 57}, {'hero_id': 84}],
                                                        'players': [{'gold': 188,
                                                                     'position_x': -6594.833984375,
                                                                     'position_y': -1564.8360595703125, 'last_hits': 22,
                                                                     'account_id': 63416758, 'denies': 0,
                                                                     'ultimate_state': 3, 'ultimate_cooldown': 0,
                                                                     'death': 12, 'item2': 34, 'item3': 29, 'item0': 4,
                                                                     'item1': 178, 'item4': 19, 'item5': 46,
                                                                     'hero_id': 57, 'xp_per_min': 124, 'player_slot': 1,
                                                                     'kills': 0, 'assists': 0,
                                                                     'gold_per_min': 137, 'level': 8, 'net_worth': 2738,
                                                                     'respawn_timer': 0},
                                                                    {'gold': 941, 'position_x': -3436.91748046875,
                                                                     'position_y': -6319.07373046875, 'last_hits': 3,
                                                                     'account_id': 121506419, 'denies': 2,
                                                                     'ultimate_state': 3, 'ultimate_cooldown': 0,
                                                                     'death': 6, 'item2': 40, 'item3': 92, 'item0': 34,
                                                                     'item1': 42, 'item4': 29, 'item5': 43,
                                                                     'hero_id': 84, 'xp_per_min': 138, 'player_slot': 2,
                                                                     'kills': 1, 'assists': 3, 'gold_per_min': 144,
                                                                     'level': 9, 'net_worth': 3096, 'respawn_timer': 0},
                                                                    {'gold': 1024,
                                                                     'position_x': -3999.3671875,
                                                                     'position_y': -4004.88330078125, 'last_hits': 114,
                                                                     'account_id': 100527967, 'denies': 4,
                                                                     'ultimate_state': 3, 'ultimate_cooldown': 0,
                                                                     'death': 9, 'item2': 125, 'item3': 46, 'item0': 63,
                                                                     'item1': 127, 'item4': 88, 'item5': 162,
                                                                     'hero_id': 99, 'xp_per_min': 454, 'player_slot': 3,
                                                                     'kills': 3, 'assists': 6,
                                                                     'gold_per_min': 347, 'level': 17,
                                                                     'net_worth': 9749, 'respawn_timer': 14},
                                                                    {'gold': 356, 'position_x': -6676.2236328125,
                                                                     'position_y': -6430.51123046875, 'last_hits': 91,
                                                                     'account_id': 226029439, 'denies': 7,
                                                                     'ultimate_state': 3, 'ultimate_cooldown': 0,
                                                                     'death': 7, 'item2': 63, 'item3': 88, 'item0': 79,
                                                                     'item1': 36, 'item4': 21, 'item5': 23,
                                                                     'hero_id': 15, 'xp_per_min': 359, 'player_slot': 4,
                                                                     'kills': 2, 'assists': 5, 'gold_per_min': 294,
                                                                     'level': 15, 'net_worth': 8281,
                                                                     'respawn_timer': 0}, {'gold': 228,
                                                                                           'position_x': -6361.521484375,
                                                                                           'position_y': -1119.7244873046875,
                                                                                           'last_hits': 117,
                                                                                           'account_id': 100307334,
                                                                                           'denies': 20,
                                                                                           'ultimate_state': 3,
                                                                                           'ultimate_cooldown': 0,
                                                                                           'death': 7, 'item2': 147,
                                                                                           'item3': 46, 'item0': 50,
                                                                                           'item1': 172, 'item4': 2,
                                                                                           'item5': 75, 'hero_id': 35,
                                                                                           'xp_per_min': 473,
                                                                                           'player_slot': 5, 'kills': 7,
                                                                                           'assists': 4,
                                                                                           'gold_per_min': 385,
                                                                                           'level': 17,
                                                                                           'net_worth': 11063,
                                                                                           'respawn_timer': 0}],
                                                        'tower_state': 1840, 'score': 14},
                'dire': {
                'abilities': [{'ability_id': 5044, 'ability_level': 4}, {'ability_id': 5045, 'ability_level': 4},
                              {'ability_id': 5046, 'ability_level': 4}, {'ability_id': 5047, 'ability_level': 2}],
                'bans': [{'hero_id': 25}, {'hero_id': 75}, {'hero_id': 95},
                         {'hero_id': 41}, {'hero_id': 7}], 'barracks_state': 63,
                'picks': [{'hero_id': 26}, {'hero_id': 39}, {'hero_id': 28}, {'hero_id': 16}, {'hero_id': 81}],
                'players': [{'gold': 1388, 'position_x': 7138.625, 'position_y': 6154.5625, 'last_hits': 135,
                             'account_id': 147686863, 'denies': 5, 'ultimate_state': 3, 'ultimate_cooldown': 0,
                             'death': 1, 'item2': 100, 'item3': 36, 'item0': 39, 'item1': 96, 'item4': 63, 'item5': 108,
                             'hero_id': 39, 'xp_per_min': 503, 'player_slot': 1, 'kills': 14, 'assists': 14,
                             'gold_per_min': 502, 'level': 18, 'net_worth': 16223, 'respawn_timer': 0},
                            {'gold': 1958, 'position_x': 4435.85693359375, 'position_y': 4539.37109375,
                             'last_hits': 201, 'account_id': 92255167,
                             'denies': 8, 'ultimate_state': 1, 'ultimate_cooldown': 67, 'death': 1, 'item2': 36,
                             'item3': 158, 'item0': 147, 'item1': 63, 'item4': 164, 'item5': 51, 'hero_id': 81,
                             'xp_per_min': 574, 'player_slot': 2, 'kills': 8, 'assists': 10, 'gold_per_min': 543,
                             'level': 19, 'net_worth': 18983, 'respawn_timer': 0}, {'gold': 710,
                                                                                    'position_x': 1111.3828125,
                                                                                    'position_y': 434.49981689453125,
                                                                                    'last_hits': 32,
                                                                                    'account_id': 55951080, 'denies': 1,
                                                                                    'ultimate_state': 3,
                                                                                    'ultimate_cooldown': 0,
                                                                                    'death': 5, 'item2': 1,
                                                                                    'item3': 188, 'item0': 34,
                                                                                    'item1': 180, 'item4': 0,
                                                                                    'item5': 108, 'hero_id': 16,
                                                                                    'xp_per_min': 349, 'player_slot': 3,
                                                                                    'kills': 10, 'assists': 16,
                                                                                    'gold_per_min': 313, 'level': 15,
                                                                                    'net_worth': 8910,
                                                                                    'respawn_timer': 0},
                            {'gold': 820, 'position_x': -4580.302734375, 'position_y': -5127.15966796875,
                             'last_hits': 63,
                             'account_id': 77961152, 'denies': 3, 'ultimate_state': 3, 'ultimate_cooldown': 0,
                             'death': 3, 'item2': 63, 'item3': 125, 'item0': 1, 'item1': 116, 'item4': 36, 'item5': 46,
                             'hero_id': 28, 'xp_per_min': 509, 'player_slot': 4, 'kills': 7, 'assists': 15,
                             'gold_per_min': 356, 'level': 18, 'net_worth': 11270, 'respawn_timer': 0}, {'gold': 579,
                                                                                                         'position_x': -3844.8359375,
                                                                                                         'position_y': -3882.26220703125,
                                                                                                         'last_hits': 20,
                                                                                                         'account_id': 117791899,
                                                                                                         'denies': 26,
                                                                                                         'ultimate_state': 2,
                                                                                                         'ultimate_cooldown': 0,
                                                                                                         'death': 4,
                                                                                                         'item2': 23,
                                                                                                         'item3': 73,
                                                                                                         'item0': 214,
                                                                                                         'item1': 34,
                                                                                                         'item4': 21,
                                                                                                         'item5': 60,
                                                                                                         'hero_id': 26,
                                                                                                         'xp_per_min': 317,
                                                                                                         'player_slot': 5,
                                                                                                         'kills': 1,
                                                                                                         'assists': 10,
                                                                                                         'gold_per_min': 213,
                                                                                                         'level': 14,
                                                                                                         'net_worth': 5504,
                                                                                                         'respawn_timer': 3}],
                'tower_state': 1975, 'score': 41}, 'roshan_respawn_timer': 0},
 'dire_team': {'team_name': 'Kehel Lella', 'team_id': 2270140, 'team_logo': 31864179201787629, 'complete': True},
 'players': [{'team': 2, 'hero_id': 0,
              'account_id': 110709163, 'name': 'T3rror\u2122'},
             {'team': 1, 'hero_id': 39, 'account_id': 147686863, 'name': 'Rape Rape Rape'}, {'team': 1, 'hero_id':
         28, 'account_id': 77961152, 'name': 'ShOcKeR!!'},
             {'team': 1, 'hero_id': 16, 'account_id': 55951080, 'name': '2sec'}, {'team': 1, 'hero_id': 81,
                                                                                  'account_id': 92255167,
                                                                                  'name': 'K-L.Harttty'},
             {'team': 1, 'hero_id': 26, 'account_id': 117791899, 'name': 'TTY'}, {'team': 2, 'hero_id': 0,
                                                                                  'account_id': 84763735,
                                                                                  'name': 'BW | Zero'},
             {'team': 2, 'hero_id': 0, 'account_id': 16928459, 'name': 'Touch Me Where It Burns'},
             {'team': 0, 'hero_id': 99, 'account_id': 100527967, 'name': 'Dilanga'},
             {'team': 0, 'hero_id': 35, 'account_id': 100307334, 'name': 'Mama_Miami'},
             {'team': 0, 'hero_id': 15, 'account_id': 226029439, 'name': 'Booom'},
             {'team': 0, 'hero_id': 84, 'account_id': 121506419, 'name': u"''Martin''"},
             {'team': 0, 'hero_id': 57, 'account_id': 63416758, 'name': 'aFrO'},
             {'team': 2, 'hero_id': 0, 'account_id': 86832861, 'name': 'Dirty'}],
 'radiant_series_wins': 0, 'league_tier': 1, 'dire_series_wins': 0, 'match_id': 1400540131}

